include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  hx8379a_fwvga_dsi_vdo_txd.o
obj-y   +=  ili9806e_fwvga_dsi_vdo_tkc.o
obj-y   +=  ili9806e_fwvga_dsi_vdo_txd.o
obj-y   +=  ili9806e_fwvga_dsi_vdo_djn.o