#ptgen script for Kernel

MTK_PLATFORM = $(shell echo $(CONFIG_MTK_PLATFORM) |sed 's/\(.*\)/\U\1/')
#BASE_PROJECT= $(shell echo $(CONFIG_ARCH_MTK_PROJECT) | sed 's/\(.*\)/\L\1/' | sed 's/ /*/g' ) 
BASE_PROJECT= $(shell echo $(CONFIG_ARCH_MTK_PROJECT) )
#BASE_PROJECT= $(CONFIG_ARCH_MTK_PROJECT)

MTK_TARGET_PROJECT=$(BASE_PROJECT)

#input file for ptgen
PTGEN_PERL = $(PWD)/../device/mediatek/build/build/tools/ptgen/$(MTK_PLATFORM)/ptgen.pl
PTGENXLS_PERL = $(PWD)/../device/mediatek/build/build/tools/ptgen/$(MTK_PLATFORM)/ptgen_xls.pl

#find the associated partition table from project setting
PTGEN_XLS:=$(shell PLATFORM=${MTK_PLATFORM} PROJECT=${BASE_PROJECT} perl ${PTGENXLS_PERL})

#OUT_PATH
PTGEN_KERNEL_OUT=${objtree}/PTGEN/inc
TMP_OUT_PATH=${objtree}/PTGEN_TMP
#PTGEN_PROJECT_OUT=$(PWD)/../out/target/product/${MTK_TARGET_PROJECT}/obj/KERNEL_OBJ/PTGEN/inc

PTGEN_FILE_LIST += $(PTGEN_KERNEL_OUT)/partition_define.h
archprepare : $(PTGEN_FILE_LIST)
export PTGEN_FILE_LIST


#MTK_LCA_SUPPORT = $(CONFIG_MTK_LCA_SUPPORT)
#MTK_NAND_PAGE_SIZE = $(CONFIG_MTK_NAND_PAGE_SIZE)
#MTK_NAND_PAGE_SIZE = 2K
#MTK_EMMC_SUPPORT = yes
#MTK_LDVT_SUPPORT = $(CONFIG_MTK_LDVT_SUPPORT)
#MTK_EMMC_SUPPORT_OTP = $(CONFIG_MTK_EMMC_SUPPORT_OTP)
#MTK_SHARED_SDCARD = $(CONFIG_MTK_SHARED_SDCARD)
#MTK_DRM_KEY_MNG_SUPPORT = $(CONFIG_MTK_DRM_KEY_MNG_SUPPORT)
#MTK_IN_HOUSE_TEE_SUPPORT = $(CONFIG_MTK_IN_HOUSE_TEE_SUPPORT)
#TARGET_BUILD_VARIANT = $(CONFIG_TARGET_BUILD_VARIANT)
#MTK_CIP_SUPPORT = $(CONFIG_MTK_CIP_SUPPORT)
#MTK_NAND_UBIFS_SUPPORT = $(CONFIG_MTK_NAND_UBIFS_SUPPORT)
#PL_MODE = $(CONFIG_PL_MODE)
#MTK_YAML_SCATTER_FILE_SUPPORT = $(CONFIG_MTK_YAML_SCATTER_FILE_SUPPORT)
#FULL_PROJECT = $(CONFIG_FULL_PROJECT)
#MTK_SPI_NAND_SUPPORT = $(CONFIG_MTK_SPI_NAND_SUPPORT)
#MTK_FAT_ON_NAND = $(CONFIG_MTK_FAT_ON_NAND)
#MTK_COMBO_NAND_SUPPORT = $(CONFIG_MTK_COMBO_NAND_SUPPORT)
#TRUSTONIC_TEE_SUPPORT = $(CONFIG_TRUSTONIC_TEE_SUPPORT)
#MTK_PERSIST_PARTITION_SUPPORT = $(CONFIG_MTK_PERSIST_PARTITION_SUPPORT)

MTK_LCA_SUPPORT = $(CONFIG_MTK_LCA_SUPPORT)
#MTK_NAND_PAGE_SIZE = $(CONFIG_MTK_NAND_PAGE_SIZE)
MTK_NAND_PAGE_SIZE = 2K
MTK_EMMC_SUPPORT = yes
MTK_LDVT_SUPPORT = $(CONFIG_MTK_LDVT_SUPPORT)
MTK_EMMC_SUPPORT_OTP = $(CONFIG_MTK_EMMC_SUPPORT_OTP)
MTK_SHARED_SDCARD = $(CONFIG_MTK_SHARED_SDCARD)
MTK_DRM_KEY_MNG_SUPPORT = $(CONFIG_MTK_DRM_KEY_MNG_SUPPORT)
MTK_IN_HOUSE_TEE_SUPPORT = $(CONFIG_MTK_IN_HOUSE_TEE_SUPPORT)
TARGET_BUILD_VARIANT = $(CONFIG_TARGET_BUILD_VARIANT)
MTK_CIP_SUPPORT = $(CONFIG_MTK_CIP_SUPPORT)
MTK_NAND_UBIFS_SUPPORT = $(CONFIG_MTK_NAND_UBIFS_SUPPORT)
PL_MODE = $(CONFIG_PL_MODE)
#MTK_YAML_SCATTER_FILE_SUPPORT = $(CONFIG_MTK_YAML_SCATTER_FILE_SUPPORT)
MTK_YAML_SCATTER_FILE_SUPPORT = yes
FULL_PROJECT = $(CONFIG_FULL_PROJECT)
MTK_SPI_NAND_SUPPORT = $(CONFIG_MTK_SPI_NAND_SUPPORT)
MTK_FAT_ON_NAND = $(CONFIG_MTK_FAT_ON_NAND)
MTK_COMBO_NAND_SUPPORT = $(CONFIG_MTK_COMBO_NAND_SUPPORT)
TRUSTONIC_TEE_SUPPORT = $(CONFIG_TRUSTONIC_TEE_SUPPORT)
MTK_PERSIST_PARTITION_SUPPORT = $(CONFIG_MTK_PERSIST_PARTITION_SUPPORT)

-include $(PWD)/../device/*/${MTK_TARGET_PROJECT}/ProjectConfig.mk

export MTK_LCA_SUPPORT
export MTK_NAND_PAGE_SIZE
export MTK_EMMC_SUPPORT
export MTK_LDVT_SUPPORT
export MTK_EMMC_SUPPORT_OTP
export MTK_SHARED_SDCARD
export MTK_DRM_KEY_MNG_SUPPORT
export MTK_IN_HOUSE_TEE_SUPPORT
export TARGET_BUILD_VARIANT
export MTK_CIP_SUPPORT
export MTK_NAND_UBIFS_SUPPORT
export PL_MODE
export MTK_YAML_SCATTER_FILE_SUPPORT
export FULL_PROJECT
export MTK_SPI_NAND_SUPPORT
export MTK_FAT_ON_NAND
export MTK_COMBO_NAND_SUPPORT
export TRUSTONIC_TEE_SUPPORT
export MTK_DRM_KEY_MNG_SUPPORT
export MTK_PERSIST_PARTITION_SUPPORT

${PTGEN_FILE_LIST}: ${PTGEN_PERL} ${PTGEN_XLS}
	@PLATFORM=${MTK_PLATFORM} \
	PROJECT=${CONFIG_ARCH_MTK_PROJECT}	\
	MTK_TARGET_PROJECT=${MTK_TARGET_PROJECT} \
	PTGEN_XLS=${PTGEN_XLS} \
	PTGEN_ENV="KERNEL" \
	PTGEN_KERNEL_OUT=${PTGEN_KERNEL_OUT} \
	TMP_OUT_PATH=${TMP_OUT_PATH} \
	perl ${PTGEN_PERL}

